# Generated by Django 2.1 on 2018-09-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociaLINK', '0002_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
