# Generated by Django 2.1 on 2018-09-15 03:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociaLINK', '0005_notification_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
