# Generated by Django 2.1 on 2018-09-15 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociaLINK', '0006_notification_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
