# Generated by Django 2.1 on 2018-09-15 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sociaLINK', '0007_auto_20180915_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='otherEndUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otherEnd', to=settings.AUTH_USER_MODEL),
        ),
    ]
