# Generated by Django 2.1 on 2018-09-16 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sociaLINK', '0008_notification_otherenduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='isImpressed',
            field=models.BooleanField(default=False),
        ),
    ]
