# Generated by Django 2.1 on 2018-09-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sociaLINK', '0011_auto_20180916_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='isImpressed',
        ),
    ]
